### ISSUE TITLE
Fix device_tracker component

### ISSUE THREAD

**Issue by Edo78** [Drakulix/googlehome#10]
I just installed and configured this component in a docker container.
Sadly the only thing I can see is this error in the logs
```
ERROR (MainThread) [homeassistant.components.device_tracker] Setup of platform googlehome is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```

What can I check?

**Comment by Drakulix** [comment]
You can enable debug logging for the component.
In your configuration.yaml you need to add something like:

```yaml
logger:
  default: info
  logs:
    custom_components.googlehome: debug
```

Also please note, that this error message currently is normal. Depending on the general amount of devices setup in google home the integration has to check multiple tokens per device. Setup can currently take a bit more then a minute.

Are your google home devices all found by the 'cast' integration? This intergration re-uses the discovery process of the cast component. (Which also means it has to be setup for this one to work correctly.)

**Comment by Edo78** [comment]
The debug show a lot more info like
```
2020-11-16 16:46:17 DEBUG (MainThread) [custom_components.googlehome.device_tracker] Checking Devices on 10.10.10.14
2020-11-16 16:46:17 DEBUG (MainThread) [custom_components.googlehome] Updating Google Home bluetooth for 10.10.10.14
2020-11-16 16:46:18 DEBUG (MainThread) [custom_components.googlehome] [{'device_class': 0, 'device_type': 2, 'expected_profiles': 0, 'mac_address': 'd8:f4:fb:8d:9e:01', 'name': 'MI Band 2', 'rssi': -74}, {'device_class': 0, 'device_type': 2, 'expected_profiles': 0, 'mac_address': '6f:41:45:bb:8f:83', 'name': '', 'rssi': -77}, {'device_class': 0, 'device_type': 2, 'expected_profiles': 0, 'mac_address': 'fb:7d:d1:8e:38:98', 'name': 'Mi Smart Band 5', 'rssi': -82}, {'device_class': 3671076, 'device_type': 1, 'expected_profiles': 0, 'mac_address': '10:c2:5a:1e:53:89', 'name': 'TIM_BOX 5084', 'rssi': -93}]
```
(I'm interested in the my bands so they should be fine)

I still can't figure it out where to check, in HA, for the device this component tracks. If I search for `tracker` in the developer tools I only find the previously tracked devices. If I check the integration page this one doesn't show any devices or entities. Should I try to change the default -70 RSSI threshold?

BTW there are also a lot of
```
2020-11-16 16:47:28 DEBUG (MainThread) [custom_components.googlehome] Scan failed, scheduling token update
```

**Comment by Drakulix** [comment]
Well all your devices have a lower RSSI then -70, meaning they should [be filtered out](https://github.com/Drakulix/googlehome/blob/master/custom_components/googlehome/device_tracker.py#L118).

Lowering the RSSI value *should* help. However you might need to restart home-assistant for that change to take effect (I have not tested config reloading much).

Also I am still seeing similar problems on my system (I have no use-case for the device_tracker component, so I never noticed). I will investigate further. Please report back, if changing the RSSI value has any effect.

**Comment by Edo78** [comment]
I lowered the RSSI to -100 and restarted HA.
Then in the log I found (among others)
```
{'device_class': 0, 'device_type': 2, 'expected_profiles': 0, 'mac_address': 'fb:7d:d1:8e:38:98', 'name': 'Mi Smart Band 5', 'rssi': -48}
```
so this device should be valid even with the previous threshold but I still can't see it anywhere in home assistant.

BTW should I check under `device_tracker` or somewhere else?

**Comment by Drakulix** [comment]
`device_tracker` is correct. I believe, I have found the error though. I have likely broken the device_tracker, when switching over to the UI configuration for this component. I am working on a fix as we speak.

**Comment by Drakulix** [comment]
Tag v0.3.5 (if you installed this repo via HACS you just need to update) contains a fix. :)
Please report back!

**Comment by Edo78** [comment]
It works and I'm very happy. Thank you for your work and for you fast response.

Just wandering if there's a way to config the integration with a whitelist of BT devices to track.

**Comment by Drakulix** [comment]
Well you can remove the check for "Tracking new devices" from the integrations options (just added that) once all your devices were discovered once. And then cleanup the ones you do not want (I hope that this is possible through the HA interface :sweat_smile: ).
