### ISSUE TITLE
Never device go not_home

### ISSUE THREAD

**Issue by ElGranLoky** [Drakulix/googlehome#17]
HomeAssistant: 0.117.6

I setup googlehome with hacs and start discover new devices, but the devices always keeps connected.

I change timeout for devices, but nothing happend. The devices remains in home after poweroff the bluetooth of the device.

**Comment by Drakulix** [comment]
Should be fixed by 712b19dc6fa6494052925d9a1739a415ecdcff46 released in v0.4.0.

(Please reopen if not and sorry for the late response.)
