### ISSUE TITLE
Rooted Android in VM

### ISSUE THREAD

**Issue by Megabytemb** [Drakulix/googlehome#2]
Hey there,

In your doco you note that you could used rooted android running in a VM.

can you share how you achieved this? any chance we can get that running in docker to fully automate token generation?

**Comment by Drakulix** [comment]
@Leatherface75 [has done this](https://github.com/rithvikvibhu/GHLocalApi/issues/39#issuecomment-520680686) but seems to have some issues (#1) with this integration (although I am not sure, how they related to using a VM. Technically adb connected to any android should work.) He might be able to share some more infos on this.

However I think you can just use the [android-x86](https://www.android-x86.org/) project.

About docker. Yes you *can* (with a privileged container) run something like kvm/qemu in a [docker container](https://hub.docker.com/r/ennweb/kvm). It should also be possible to craft this into something that just exposes an adb port and automagically installs the google home app, but I would not trust a privileged container, I have not built myself.

I have no use-case for this, as I have a rooted device lying around and plan to replace the setup in the future anyway, but feel free to discuss a potential VM-Setup here.

**Comment by Leatherface75** [comment]
It works fine with android-x86 project on my esxi machine.
I am using his ghproxy there i compiled 3 versions for my 3 google home minis.
Then i wrote a bash script that is running with crontab.
Normally for me tokens changes at night but if you do some changes you normally need to update other times too. It needed a lot of trial and error but i found a solution that have worked for me for a while without need to do manual work.

```
cd /tmp
adb connect 192.168.0.80
adb shell ps|grep chromecast|awk '{print $2}'|xargs adb shell kill
adb shell rm /data/data/com.google.android.apps.chromecast.app/files/*
sleep 30
adb shell monkey -p com.google.android.apps.chromecast.app -c android.intent.category.LAUNCHER 1
sleep 15
adb shell input keyevent 4
sleep 30
adb pull /data/data/com.google.android.apps.chromecast.app/files
mv home_graph.pb home_graph.pb.old
cp files/home_graph*.proto home_graph.pb
HG_CHANGED=$(diff home_graph.pb home_graph.pb.old)
if [ "$HG_CHANGED" != "" ]
then
  killall -9 ghlapi_proxy_1 ghlapi_proxy_2 ghlapi_proxy_3
  export SOURCE_IP_1=192.168.0.15
  export SOURCE_IP_2=192.168.0.30
  export SOURCE_IP_3=192.168.0.70
  export LISTEN_IP_1=192.168.0.120
  export LISTEN_IP_2=192.168.0.121
  export LISTEN_IP_3=192.168.0.122
  num=0;node decodeProtoFile.js |grep 28|cut -c10-117|while read -a tokens; do num=$((num+1)); export "TOKEN_$num=${tokens[0]}"; eval 'ghlapi_proxy_$num &'; done
else
  echo "Restarting Proxy not needed..."
fi
```

And in startup of machine i have this.

```
ip addr add 192.168.0.120/24 dev enp2s0
ip addr add 192.168.0.121/24 dev enp2s0
ip addr add 192.168.0.122/24 dev enp2s0
```

Maybe not the most beutiful solution but it works :)

**Comment by fmieres** [comment]
> Hey there,
> 
> In your doco you note that you could used rooted android running in a VM.
> 
> can you share how you achieved this? any chance we can get that running in docker to fully automate token generation?

if you still having trouble setting up a emu with rooted android using AVD, i can give you a real quick walkthrough of what i did.
I still havent achieved emulator to see chromecast devices in the network but since you can use a common google account, you'll still see the same config files.

**Comment by roflcoopter** [comment]
> > Hey there,
> > In your doco you note that you could used rooted android running in a VM.
> > can you share how you achieved this? any chance we can get that running in docker to fully automate token generation?
> 
> if you still having trouble setting up a emu with rooted android using AVD, i can give you a real quick walkthrough of what i did.
> I still havent achieved emulator to see chromecast devices in the network but since you can use a common google account, you'll still see the same config files.

do you mind detailing how you solved this?

**Comment by MeanderingCode** [comment]
> About docker. Yes you _can_ (with a privileged container) run something like kvm/qemu in a [docker container](https://hub.docker.com/r/ennweb/kvm). It should also be possible to craft this into something that just exposes an adb port and automagically installs the google home app, but I would not trust a privileged container, I have not built myself.

I have experimented with this, and the Google Home Android app will not run on an emulator (Play Services and Play Store included, based on official system images with these pre-installed). The Play Store indicates the Home app is not available on that platform, and even an experiment with an APK resulted in a message indicating "required components" were not installed, and I should reinstall from the Play Store.

**Comment by Drakulix** [comment]
Current version of this plugin does not require any adb connections anymore, so this issue no longer applies. Closing.
