### ISSUE TITLE
After deleting addon I have error

### ISSUE THREAD

**Issue by krzysiek2788** [Drakulix/googlehome#22]
When I delete this addon in HACS I have below error in Notification after HA restart:
````
Logger: homeassistant.setup
Source: setup.py:138
First occurred: 13:06:56 (1 occurrences)
Last logged: 13:06:56

Setup failed for googlehome: Integration not found.
````

**Comment by Edo78** [comment]
I have the very same error even after removing the integration (not just from HACS).
I can't figure how to solve this ...

**Comment by Edo78** [comment]
I'm not sure it's the proper way but I stopped HA and edited the file `.storage/core.config_entries` removing the whole block about `googlehome` and restarted HA (I have the docker installation)

Hope this can provide some insight

**Comment by Drakulix** [comment]
> I'm not sure it's the proper way but I stopped HA and edited the file .storage/core.config_entries removing the whole block about googlehome and restarted HA (I have the docker installation)

Yeah, that is on home-assistant/core and expected.

What happens is, that by setting up the `google_home` integration via the UI, home-assistant adds an entry in `.storage/core.config_entries`. When you remove the integration and restart home-assistant, it finds that entry, but not the integration to load it.

This is essentially the same as leaving settings for a custom integration inside your `configuration.yaml`.

What you need to do is removing the integration entry in the UI before uninstalling `google_home`! (Or manually clean up your `.storage/core.config_entries` file).
If HA does not already do so, they should probably provide a way to remove integrations that failed to load from the UI.

**Comment by Drakulix** [comment]
Anyway, there is nothing I can do about it.
If you have an issue with out HA handles this case, you should fill an issue at their repo: https://github.com/home-assistant/core
