### ISSUE TITLE
Feature request: Ability to toggle Do Not Disturb

### ISSUE THREAD

**Issue by jamieshaw** [Drakulix/googlehome#5]
Previously, before authentication was required, I was polling the Do Not Disturb REST endpoint to create a switch within Home Assistant.

Is it possible to create a switch within the custom component that calls upon `/setup/assistant/notifications` for similar effect?

**Comment by Drakulix** [comment]
Yes, this should be quite easily doable.

The underlying `googledevices` library already offers a function to poll that:
https://github.com/Drakulix/googlehome/blob/master/custom_components/googlehome/googledevices/api/cast/assistant.py#L35

One would need to add a [new `update_` function](https://github.com/Drakulix/googlehome/blob/master/custom_components/googlehome/__init__.py#L118) to query the Do Not Distrub state and add a new switch component (very similar to the sensor.py), which then needs to be initialized [here](https://github.com/Drakulix/googlehome/blob/master/custom_components/googlehome/__init__.py#L95).

I have personally no use and no time for this feature. But I would gladly accept a PR implementing this functionality.
