### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Leatherface75** [Drakulix/googlehome#6]
I still have problems to get this working.
The only thing that works for me is your old ghlapi_proxy.

Now i am having this problem.

> 2020-02-17 21:18:32 ERROR (MainThread) [homeassistant.setup] Setup failed for googlehome: unknown error
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 136, in _async_setup_component
>     component = integration.get_component()
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 266, in get_component
>     cache[self.domain] = importlib.import_module(self.pkg_path)
>   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 860, in get_code
>   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/config/custom_components/googlehome/__init__.py", line 68
>     print proto
>               ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(proto)?

**Comment by Leatherface75** [comment]
This is with latest version of HA but i had same problem for a few versions too.
I tried to change that print proto in init.py file but didn't help.

**Comment by Drakulix** [comment]
Are you sure you are using the latest version of my plugin?

The repository contains no 'init.py' only a `__init.py__`.

Maybe try to delete the component and install it via HACS instead.

**Comment by Leatherface75** [comment]
It was cloned directly from github.
In HACS i can't find the plugin at all.

What do you mean with this?

> The repository contains no 'init.py' only a 'init.py'.

**Comment by Drakulix** [comment]
> It was cloned directly from github.
> In HACS i can't find the plugin at all.

You can add this github repo as a custom repository and it will install via hacs.

> 
> What do you mean with this?
> 
> > The repository contains no 'init.py' only a `__init.py__`.

Markdown was hiding the underscores.

**Comment by Leatherface75** [comment]
Well i can do that but can't see how that would make a difference.

> commit 30bbe1f817abd98aa472e5dc43d866bba189aa7d (HEAD -> master, tag: v0.2.1, origin/master, origin/HEAD)
> Author: Victor Brekenfeld <github@drakulix.de>
> Date:   Fri Oct 4 19:28:51 2019 +0200
> 
>     Fixup, my bad
> 

Latest commit from my 'git clone' is that wrong?

**Comment by Leatherface75** [comment]
Adding in HACS doesn't work either.

> An error ocoured while processing
> Exception: HacsException
> Message: GitHub returned 404 for https://api.github.com/repos/Drakulix/googlehome/
> Could not add this repository, make sure it is compliant with HACS.

**Comment by Drakulix** [comment]
> https://api.github.com/repos/Drakulix/googlehome/

Correct link would be: https://github.com/Drakulix/googlehome



> commit [30bbe1f]

But yes, that is the right commit.


Could you show me, where that `print proto` is supposed to be in my repo? Because there is none, which is why I was suspecting, that you were using an old version: https://github.com/Drakulix/googlehome/search?p=1&q=print&unscoped_q=print

**Comment by Leatherface75** [comment]
Yes that's what i have there error message responds with another link.
I will check more in a while this is strange because i removed the whole thing and restarted and then i replaced with a fresh new 'git clone' and then restarted again.
Without removing the whole plugin first i was not even able to restart Home Assistant.

**Comment by Drakulix** [comment]
> Yes that's what i have there error message responds with another link.
> I will check more in a while this is strange because i removed the whole thing and restarted and then i replaced with a fresh new 'git clone' and then restarted again.
> Without removing the whole plugin first i was not even able to restart Home Assistant.

This sounds like you setup is somewhat unusual. I have no clear idea, how to debug this further. Sorry :(

**Comment by Leatherface75** [comment]
It's standard hassio installation so it's nothing special but still trying to find out why this happens.

**Comment by Leatherface75** [comment]
Seems the problem with adding repo in HACS was that i added as plugin and not integration.

**Comment by Drakulix** [comment]
Well, at least we got that solved, but if it is still not working, I am a bit lost.
I do not know how to help you and I am not using the plugin myself anymore, as I have just replaced my google home's and only used this extension (or the ghlapi-proxy) as a stepping stone to ease the migration. At this point I can only recommend, you keep using the ghlapi_proxy instead.
