### ISSUE TITLE
Home Assistant hangs

### ISSUE THREAD

**Issue by Leatherface75** [Drakulix/googlehome#7]
With the latest changes everything works fine except that it causes Home Assistant to hang everyday and i have to restart it to get it working again until next day. When i removed the addon this behaviour stopped again.

**Comment by Drakulix** [comment]
Interesting. Mine is working fine for days.
But I dont consider the current version stable yet.

Do you have any backtraces or other interesting log entries, that might help finding the cause?

**Comment by Leatherface75** [comment]
No but can try to fix it later and see if i can find something.

**Comment by Drakulix** [comment]
I have also published a new version, just in case you were not using the master branch version.
I have since published some fixes, which might resolve your problems.

**Comment by Leatherface75** [comment]
Yes it's the latest master version i am using let's see in some day what it says.
Or is 0.3.2 on HACS newer version? Maybe it was 0.3.1 i was using so let's see what happens.

**Comment by Leatherface75** [comment]
After little more than 24 hours with 0.3.2 it's still up and running.
Let's hope it doesn't stop working now only because i am saying that :)

**Comment by Drakulix** [comment]
Had a hang today and was able to capture a somewhat comprehensive log.
I will try to debug this later, but this is definitely a sporadic issue.
I have no clue yet, what is causing this though.

**Comment by Leatherface75** [comment]
Ok here it has worked so far after i updated to 0.3.2 so in my case i think it was that i was using 0.3.1 and not master version as i thought. Maybe there is other issues too. I have updated to latest HA release too i don't know if it has something to do with that.
It's not crashing every day anymore atleast.

**Comment by Drakulix** [comment]
It been almost two weeks and I have not noticed any hangs anymore. Have you @Leatherface75 ?
Otherwise I would close this issue.

**Comment by Leatherface75** [comment]
Same here so we can close it.
